FROM docker.elastic.co/elasticsearch/elasticsearch:6.4.3

# Copy custom elasticsearch.yml
COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# Set environment variables
ENV discovery.type=single-node
ENV bootstrap.memory_lock=true
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"

# Expose ports
EXPOSE 9200 9300

# Set permissions
USER root
RUN chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data
USER elasticsearch 